services:
  qsticky:
    image: ghcr.io/monstermuffin/qsticky:latest
    network_mode: "service:gluetun"       # Use Gluetun network
    volumes:
      - ./gluetun:/tmp/gluetun:ro         # Read-only access to port file
    environment:
      - QBITTORRENT_HOST=localhost
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USER=admin    # Match your qBittorrent credentials
      - QBITTORRENT_PASS=adminadmin
      - LOG_LEVEL=INFO
    restart: unless-stopped
    # user: "1000:1000" # Optional: run as same user as qBittorrent if needed