services:
  qsticky:
    image: ghcr.io/monstermuffin/qsticky:latest
    network_mode: "container:gluetun"
    environment:
      # qbittorrent settings
      QBITTORRENT_HOST: localhost
      QBITTORRENT_HTTPS: false
      QBITTORRENT_PORT: 8080
      QBITTORRENT_USER: admin
      QBITTORRENT_PASS: adminadmin
      # gluetun settings
      GLUETUN_AUTH_TYPE: apikey
      GLUETUN_APIKEY: put_api_key_here
      # qSticky settings
      LOG_LEVEL: INFO
    healthcheck:
      test: ["CMD", "cat /app/health/status.json | grep -q '\"api_connected\": true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: on-failure
